// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXa08KUmT8idI3RPnAkLiapf5vuOLhOT4',
    appId: '1:618654470366:web:211524e06c2bbc8447f24f',
    messagingSenderId: '618654470366',
    projectId: 'kaylasoftmt',
    authDomain: 'kaylasoftmt.firebaseapp.com',
    storageBucket: 'kaylasoftmt.appspot.com',
    measurementId: 'G-7R2GPDH7D4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeg0eBthUbbSs90GCC6QXREdpR3kFkxPs',
    appId: '1:618654470366:android:ec714fa20f93b5d847f24f',
    messagingSenderId: '618654470366',
    projectId: 'kaylasoftmt',
    storageBucket: 'kaylasoftmt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAS4gAupVFUJkqAbHr8dEmudvUBtPxchck',
    appId: '1:618654470366:ios:bde45b6ed199794a47f24f',
    messagingSenderId: '618654470366',
    projectId: 'kaylasoftmt',
    storageBucket: 'kaylasoftmt.appspot.com',
    iosBundleId: 'com.example.kaylaSoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAS4gAupVFUJkqAbHr8dEmudvUBtPxchck',
    appId: '1:618654470366:ios:bde45b6ed199794a47f24f',
    messagingSenderId: '618654470366',
    projectId: 'kaylasoftmt',
    storageBucket: 'kaylasoftmt.appspot.com',
    iosBundleId: 'com.example.kaylaSoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXa08KUmT8idI3RPnAkLiapf5vuOLhOT4',
    appId: '1:618654470366:web:6c66e27a5a24bddd47f24f',
    messagingSenderId: '618654470366',
    projectId: 'kaylasoftmt',
    authDomain: 'kaylasoftmt.firebaseapp.com',
    storageBucket: 'kaylasoftmt.appspot.com',
    measurementId: 'G-P9HKKXW1J7',
  );
}
